language: node_js

node_js:
    - "16"

sudo: required

git:
    submodules: false

dist: xenial
services:
  - xvfb

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
    - echo "$PATH"
    - wget http://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip #download chrome
    - sudo mkdir /home/travis/chrome                                                #chrome dir create
    - sudo unzip chromedriver_linux64.zip -d /home/travis/chrome/                   #unzip chrome
    - export PATH=$PATH:"/home/travis/chrome/"                                      #export to $PATH
    - "export DISPLAY=:99.0"                                                        #set display
    - npm run build                                                                 #build angular

script:
    - npm test
